# Generated by Django 5.0.1 on 2025-12-04 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('color', models.CharField(default='#6366F1', max_length=7, verbose_name='Color')),
                ('icon', models.CharField(default='tag', max_length=50, verbose_name='Icono')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoría Secundaria',
                'verbose_name_plural': 'Categorías Secundarias',
                'ordering': ['name'],
            },
        ),
    ]
