# Generated by Django 5.0.1 on 2025-12-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_secondarycategory'),
        ('transactions', '0005_purchaseitem_is_ant_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='secondary_categories',
            field=models.ManyToManyField(blank=True, related_name='purchase_items', to='categories.secondarycategory', verbose_name='Categorías Secundarias'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='secondary_categories',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='categories.secondarycategory', verbose_name='Categorías Secundarias'),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto'), ('transferencia', 'Transferencia'), ('ajuste', 'Ajuste')], max_length=15, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto'), ('transferencia', 'Transferencia'), ('ajuste', 'Ajuste')], max_length=15, verbose_name='Tipo'),
        ),
    ]
