# Generated by Django 5.0.1 on 2025-12-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('CLP', 'Peso Chileno'), ('USD', 'Dólar')], default='CLP', max_length=3, verbose_name='Moneda'),
        ),
    ]
