import {
  HomeIcon,
  TruckIcon,
  BanknotesIcon,
  CakeIcon,
  HeartIcon,
  BoltIcon,
  FilmIcon,
  WalletIcon,
  AcademicCapIcon,
  ComputerDesktopIcon,
  GiftIcon,
  ShoppingBagIcon,
  GlobeAltIcon,
  SparklesIcon,
  TagIcon,
  ShoppingCartIcon,
  DevicePhoneMobileIcon,
  FireIcon,
  BeakerIcon,
  BookOpenIcon,
  WifiIcon,
  LightBulbIcon,
  CreditCardIcon,
  BuildingLibraryIcon,
  MapPinIcon,
  BriefcaseIcon,
  ChartBarIcon,
  CogIcon,
  DocumentTextIcon,
  LockClosedIcon,
  CurrencyDollarIcon,
} from '@heroicons/vue/24/outline'

export const iconMap = {
  'hogar': HomeIcon,
  'transporte': TruckIcon,
  'sueldo_ingresos': BanknotesIcon,
  'comida': CakeIcon,
  'mascotas': HeartIcon,
  'deporte': FireIcon,
  'deporte_futbol': BoltIcon,
  'deporte_gimnasio': FireIcon,
  'salud': HeartIcon,
  'farmacia': BeakerIcon,
  'entretenimiento': FilmIcon,
  'musica': SparklesIcon,
  'libros': BookOpenIcon,
  'ahorro': WalletIcon,
  'educacion': AcademicCapIcon,
  'tecnologia': ComputerDesktopIcon,
  'regalos': GiftIcon,
  'compras': ShoppingCartIcon,
  'supermercado': ShoppingCartIcon,
  'ropa': ShoppingBagIcon,
  'viajes': GlobeAltIcon,
  'restaurantes': CakeIcon,
  'dulces_golosinas': SparklesIcon,
  'snacks': BoltIcon,
  'servicios': LightBulbIcon,
  'internet': WifiIcon,
  'telefono': DevicePhoneMobileIcon,
  'bancos': BuildingLibraryIcon,
  'seguros': LockClosedIcon,
  'impuestos': DocumentTextIcon,
  'freelance': BriefcaseIcon,
  'inversiones': ChartBarIcon,
  'gasolina': TruckIcon,
  'estacionamiento': MapPinIcon,
  'mantenimiento': CogIcon,
  'arte': SparklesIcon,
  'belleza': GiftIcon,
  'otros': TagIcon,
}

export function getIconComponent(iconName) {
  return iconMap[iconName] || iconMap['otros']
}

export const iconLabels = {
  'hogar': 'Hogar',
  'transporte': 'Transporte',
  'sueldo_ingresos': 'Sueldo/Ingresos',
  'comida': 'Comida',
  'mascotas': 'Mascotas',
  'deporte': 'Deporte',
  'deporte_futbol': 'Deporte - Fútbol',
  'deporte_gimnasio': 'Deporte - Gimnasio',
  'salud': 'Salud',
  'farmacia': 'Farmacia',
  'entretenimiento': 'Entretenimiento',
  'musica': 'Música',
  'libros': 'Libros',
  'ahorro': 'Ahorro',
  'educacion': 'Educación',
  'tecnologia': 'Tecnología',
  'regalos': 'Regalos',
  'compras': 'Compras',
  'supermercado': 'Supermercado',
  'ropa': 'Ropa',
  'viajes': 'Viajes',
  'restaurantes': 'Restaurantes',
  'dulces_golosinas': 'Dulces/Golosinas',
  'snacks': 'Snacks',
  'servicios': 'Servicios',
  'internet': 'Internet',
  'telefono': 'Teléfono',
  'bancos': 'Bancos',
  'seguros': 'Seguros',
  'impuestos': 'Impuestos',
  'freelance': 'Freelance',
  'inversiones': 'Inversiones',
  'gasolina': 'Gasolina',
  'estacionamiento': 'Estacionamiento',
  'mantenimiento': 'Mantenimiento',
  'arte': 'Arte',
  'belleza': 'Belleza',
  'otros': 'Otros',
}

